const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:1365,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file://'+path.resolve('what-happens-to-a-moment.html'));await p.waitForSelector('.title-screen');
const results=await p.evaluate(()=>{
 const saved=render;render=()=>{};const failures=[];const seen=new Set();const routes=[];
 function play(seed,first,variant){resetGame(seed);startGame();let count=0;while(state.screen!=='ending'&&count++<100){if(state.screen==='outcome'){nextTurn();continue;}const sc=activeScene();let i=state.screen==='turn'&&state.turn===0?first:(variant+state.turn+state.history.length)%sc.choices.length;if(sc.choices[i].need&&!sc.choices[i].need())i=sc.choices.findIndex(c=>!c.need||c.need());if(i<0)throw Error('dead end');state.screen==='mini'?chooseMini(i):selectChoice(i);}if(state.screen!=='ending')throw Error('No ending');return {history:state.history.map(h=>[h.event,h.choiceId]),events:state.events.map(e=>[e.turn,e.type]),vars:{...state.vars},diagnosis:movementDiagnosis(calculateEnding()).state};}
 for(let f=0;f<4;f++)for(let v=0;v<25;v++){const r=play(512+v,f,v);if(state.history.filter(h=>!h.mini).length!==12)throw Error('Turn count');if(state.events.length!==6)throw Error('Event slots');seen.add(r.diagnosis);routes.push(r);}
 const a=play(123,2,4),a2=play(123,2,4);if(JSON.stringify(a)!==JSON.stringify(a2))throw Error('Seed mismatch');
 const variants=new Set();for(let seed=1;seed<=8;seed++)variants.add(JSON.stringify(play(seed,2,4).events));if(variants.size<2)throw Error('No external variation');
 const r=play(123,2,4);if(!r.history.some(h=>h[0]==='Bigger Than What?')||!r.history.some(h=>h[0].includes('First Disagreement')))throw Error('Missing widening');
 resetGame(7);state.turn=10;state.flags.clear();state.vars.mob=0;state.access=0;state.trust=0;state.staff=false;state.screen='turn';if(currentTurn().choices.slice(0,4).some(c=>!c.need||c.need()))throw Error('Protection gate');if(currentTurn().choices[4].need)throw Error('Fallback gated');
 const beforeRng=state.rng,beforeEvents=state.events.length;renderTurn();if(state.rng!==beforeRng||state.events.length!==beforeEvents)throw Error('Rendering rerolls events');
 resetGame(9);state.turn=7;state.structure='membership';state.screen='turn';if(currentTurn().choices[1].need())throw Error('Instant membership');
 state.structure='council';state.governance='council';state.trust=0;if(currentTurn().choices[2].need())throw Error('Dead alliance returns');
 render=saved;resetGame();return {routes:routes.length,states:[...seen]};});
assert.deepEqual(errors,[]);console.log(results);
await p.getByRole('button',{name:/Begin the year/}).click();await p.locator('.choice-card').nth(2).click();await p.getByRole('button',{name:'Continue',exact:true}).click();await p.screenshot({path:'output/moment/v4-charter.png',fullPage:true,animations:'disabled'});
for(let i=0;i<4;i++){await p.locator('.choice-card:not([disabled])').first().click();if(i<3)await p.getByRole('button',{name:'Continue',exact:true}).click();}await p.getByRole('button',{name:'Continue',exact:true}).click();await p.screenshot({path:'output/moment/v4-stay.png',fullPage:true,animations:'disabled'});
await p.getByRole('button',{name:'Start again',exact:true}).click();assert(await p.getByRole('button',{name:/Begin the year/}).isVisible());
await p.evaluate(()=>{resetGame(42);startGame();selectChoice(0);while(state.screen!=='ending'){if(state.screen==='outcome')nextTurn();else{const sc=activeScene();const i=sc.choices.findIndex(c=>!c.need||c.need());state.screen==='mini'?chooseMini(i):selectChoice(i);}}});await p.screenshot({path:'output/moment/v4-ending.png',fullPage:true,animations:'disabled'});
await p.setViewportSize({width:390,height:844});await p.screenshot({path:'output/moment/v4-ending-mobile.png',fullPage:true,animations:'disabled'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await p.evaluate(()=>{resetGame(6);startGame();selectChoice(0);nextTurn()});await p.screenshot({path:'output/moment/v4-assurance-mobile.png',fullPage:true,animations:'disabled'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);await b.close();console.log('v4: branches, chain, seeds, six draws, real prerequisites, fallback, restart and mobile passed.');})();
