const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:1365,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file://'+path.resolve('what-happens-to-a-moment.html'));await p.waitForSelector('.title-screen');
const results=await p.evaluate(()=>{const saved=render;render=()=>{};const seen=new Set();function check(b,m){if(!b)throw Error(m)}
function play(seed,first,variant){resetGame(seed);startGame();let count=0;while(state.screen!=='ending'&&count++<100){if(['outcome','bulletin'].includes(state.screen)){nextTurn();continue;}const sc=activeScene();let i=state.turn===0&&state.screen==='turn'?first:(variant+state.turn+state.history.length)%sc.choices.length;if(sc.choices[i].need&&!sc.choices[i].need())i=sc.choices.findIndex(c=>!c.need||c.need());check(i>=0,'dead end '+state.turn);state.screen==='mini'?chooseMini(i):selectChoice(i);}check(state.screen==='ending','No ending');check(state.history.filter(h=>!h.mini).length===(first===2?11:12),'turn count');check(state.events.length===4,'externality count '+first+' '+state.events.length);check(Object.values(state.vars).every(Number.isFinite)&&Number.isFinite(state.leader),'invalid scores');seen.add(movementDiagnosis(calculateEnding()).state);return JSON.stringify({history:state.history,events:state.events,ending:calculateEnding()});}
for(let f=0;f<3;f++)for(let v=0;v<100;v++)play(512+v,f,v);
check(play(123,2,4)===play(123,2,4),'seed mismatch');
resetGame(9);check(TURNS[0].choices.length===3,'opening options');state.turn=9;state.flags.clear();state.vars.mob=0;check(currentTurn().choices.every(c=>!c.need),'Turn10 gated');
state.turn=10;check(!currentTurn().choices[0].need(),'phantom lawyers');state.flags.add('BUILT_LEGAL_INFRASTRUCTURE');state.cash=0;state.staff=false;check(currentTurn().choices[0].need(),'poor legal team hidden');check(!currentTurn().choices[3].need&&!currentTurn().choices[4].need,'fallback gated');
resetGame(1);state.structure='open';Object.keys(state.vars).forEach(k=>state.vars[k]=100);state.leg=100;check(calculateEnding().endState!=='THRIVE','loose thrived');
resetGame(1);state.leader=100;state.ownership=20;state.vars.ind=0;state.vars.acc=0;state.vars.org=10;state.vars.rel=100;state.dependency=100;state.flags.add('LEADERS_JOIN_PARTIES');check(calculateEnding().future==='absorption'&&calculateEnding().mechanism==='leaders','absorption');
resetGame(1);state.vars.rel=0;state.leg=0;check(calculateEnding().endState==='SURVIVAL','survival');
resetGame(1);state.structure='membership';state.governance='membership';state.vars={rel:80,org:80,agn:80,ind:80,acc:80,mob:80};state.leg=80;state.leverage=65;['SHAPED_POST_VICTORY_ISSUE','FORCED_INDEPENDENT_OUTCOME','DELIVERED_COALITION','EVIDENCE_CAPACITY','BUILT_CHAPTERS','CRISIS_DELIVERED','VIABLE_ELECTORAL_STRATEGY','GOVERNANCE_PASSED'].forEach(f=>state.flags.add(f));check(calculateEnding().endState==='THRIVE','thrive');
state.flags.delete('SHAPED_POST_VICTORY_ISSUE');check(calculateEnding().endState!=='THRIVE','scores substitute for agenda-setting');
state.flags.add('SHAPED_POST_VICTORY_ISSUE');state.flags.delete('DELIVERED_COALITION');check(calculateEnding().endState!=='THRIVE','unused capabilities thrive');
state.flags.add('DELIVERED_COALITION');state.leader=80;state.ownership=20;state.vars.ind=40;state.flags.add('LEADERS_JOIN_PARTIES');check(calculateEnding().future==='absorption','strong absorption override');
state.vars.ind=80;check(calculateEnding().future!=='absorption','departures automatically absorb independent institution');
resetGame(3);state.flags.clear();state.flags.add('CAMPAIGN_IDENTITY');state.vars.rel=65;state.vars.org=35;state.leg=60;check(calculateEnding().endState==='RELEVANCE','media relevance');check(movementDiagnosis(calculateEnding()).verb==='Amplifies','verb');state.vars.rel=30;check(calculateEnding().endState==='SURVIVAL','faded media');
resetGame(6);state.issueSalience=92;state.space=90;state.ownership=28;state.vars.rel=40;state.mediaAttention=35;state.publicOpinion=78;check(calculateEnding().endState==='SURVIVAL','popular issue is not movement power');check(movementDiagnosis(calculateEnding()).text.includes('ownership')||movementDiagnosis(calculateEnding()).text.includes('Ownership'),'ownership diagnosis');
state.popularity=72;state.publicOpinion=35;state.mediaAttention=90;state.mediaSentiment=25;check(worldDispatch().includes('coverage')||worldDispatch().includes('Coverage'),'world dispatch');const rng=state.rng;calculateEnding();worldDispatch();check(state.rng===rng,'world render rerolls');
resetGame(7);check(state.ownership===85&&state.partyDependence===0&&state.worldHistory.length===0,'world restart');


resetGame(20);state.structure='membership';const beforeMembership=state.vars.org;completeStructure();check(state.vars.org===beforeMembership,'membership bonus too early');state.turn=7;state.screen='turn';selectChoice(2);check(state.vars.org===beforeMembership+8,'membership Turn8 bonus');
resetGame(20);state.structure='central';state.branch='stay';const beforeMidnight=JSON.stringify(state.vars);enterBulletin('midnight');check(JSON.stringify(state.vars)===beforeMidnight,'midnight second score swing');
resetGame(20);state.branch='leave';state.turn=2;state.screen='turn';selectChoice(1);check(!state.pending.some(p=>p.flag==='EVIDENCE_CAPACITY'),'legal tracker supplies schools register');
resetGame(20);state.turn=10;state.screen='turn';const beforeMLA=state.leverage;selectChoice(4);check(state.leverage===beforeMLA+4,'MLA immediate leverage');nextTurn();check(state.leverage===beforeMLA,'MLA leverage became permanent');
resetGame(20);state.leader=95;state.vars.ind=20;state.ownership=10;state.flags.add('TURN12_D_INDIVIDUAL_CHOICES');check(calculateEnding().future!=='absorption','permission equals migration');state.flags.add('LEADERS_JOIN_PARTIES');check(calculateEnding().future==='absorption','recorded migration missing');check(movementDiagnosis(calculateEnding()).text.includes('recognisable leaders'),'missing capture mechanism');
const beforeTags=JSON.stringify(TURNS[11].choices.map(c=>!c.need||c.need()));state.tags=['BUILT_LOCAL_ROOTS','BUILT_ENFORCEMENT_CAPACITY'];check(JSON.stringify(TURNS[11].choices.map(c=>!c.need||c.need()))===beforeTags,'history tags gate choices');
resetGame(12);state.turn=2;state.branch='leave';state.screen='turn';seedPressure();check(pressurePublicState().jobs.length===3,'initial commitments');assignTeam(1);assignTeam(2);assignTeam(3);check(state.pressure.assigned.length===2,'team budget');assignTeam(1);check(state.pressure.assigned.length===1,'release team');const beforeDue=state.pressure.jobs[0].due;state.turn=3;expirePressure();check(state.pressure.jobs[0].misses===1,'missed deadline');state.turn=5;expirePressure();check(state.pressure.jobs[0].status==='transferred','repeated neglect');
resetGame(12);state.turn=4;state.screen='turn';seedPressure();state.flags.add('EVIDENCE_CAPACITY');state.vars.acc=60;assignTeam(state.pressure.jobs[0].id);resolvePressure();check(state.pressure.jobs[0].status==='done','institutional relief');check(state.pressure.assigned.length===0,'team reset');resetGame();check(state.pressure.jobs.length===0,'pressure restart');
render=saved;resetGame();return {routes:300,observed:[...seen]};});console.log(results);assert.deepEqual(errors,[]);
await p.getByRole('button',{name:/Begin the year/}).click();await p.locator('.choice-card').nth(2).click();await p.getByRole('button',{name:'Continue',exact:true}).click();
for(let i=0;i<3;i++){await p.locator('.choice-card:not([disabled])').first().click();await p.getByRole('button',{name:'Continue',exact:true}).click();}
assert.equal(await p.locator('.choice-card').count(),0);await p.screenshot({path:'output/moment/v2-midnight.png',fullPage:true,animations:"disabled"});await p.getByRole('button',{name:'Continue',exact:true}).click();await p.screenshot({path:'output/moment/v2-occupation.png',fullPage:true,animations:"disabled"});
await p.getByRole('button',{name:'Start again',exact:true}).click();assert(await p.getByRole('button',{name:/Begin the year/}).isVisible());
await p.evaluate(()=>{startGame();while(state.screen!=='ending'){if(['outcome','bulletin'].includes(state.screen))nextTurn();else{const sc=activeScene(),i=sc.choices.findIndex(c=>!c.need||c.need());state.screen==='mini'?chooseMini(i):selectChoice(i);}}});await p.screenshot({path:'output/moment/v2-ending.png',fullPage:true,animations:"disabled"});await p.setViewportSize({width:390,height:844});await p.screenshot({path:'output/moment/v2-ending-mobile.png',fullPage:true,animations:"disabled"});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.evaluate(()=>{state.leader=85;state.vars.ind=25;state.ownership=20;state.vars.rel=75;state.vars.mob=70;state.flags.add('LEADERS_JOIN_PARTIES');state.flags.add('MIGRATION_NEW_REFORM_PARTY');showEnding();});await p.screenshot({path:'output/moment/v2-absorbed-mobile.png',fullPage:true,animations:'disabled'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);await b.close();})().catch(e=>{console.error(e);process.exit(1)});
