// Art direction is presentation only: all decisions and state remain in the simulation.
function masthead(edition='A political year') {return `<header class="masthead"><div class="masthead-brand"><span class="brand-mark" aria-hidden="true"></span>Civic Games Lab</div><span class="masthead-note">A political futures simulation</span><div class="masthead-actions"><span class="edition">${edition}</span>${state.screen!=='title'?'<button class="restart-button" onclick="resetGame(); window.scrollTo(0,0)">Start again</button>':''}</div></header>`;}
renderTitle=function(){app.innerHTML=`<div class="screen title-screen">${masthead('Field notes / 01')}<div class="hero-body"><div class="title-label">The resignation is real. The year is just beginning.</div><h1 class="title-main">What Happens<br>to a <em>Moment?</em></h1><p class="title-question">You created the political space.<br>Everyone else has entered it.<br>What will you build that they cannot take?</p><div class="hero-action"><button class="btn" onclick="startGame()">Begin the year <span aria-hidden="true">&nbsp; ↗</span></button><span class="hero-duration">12 turns.<br>One political year.</span></div></div><footer class="hero-footer"><span class="folio">A victory is an opening.</span><span class="fiction-note">Fictional simulation · Generated scene illustration</span></footer></div>`;};
function documentData(){
 const sc=state.screen==='outcome'?state.lastChoice.turn:activeScene();
 const title=state.screen==='outcome'?state.lastChoice.choice.label:sc.event;
 const isMini=state.screen==='mini'||(state.screen==='outcome'&&state.lastChoice.mini);
 const kind=state.mini==='funding'&&isMini?'ledger':state.mini==='assurance'&&isMini?'assurance':state.turn===4?'register':state.occupation?'night':state.turn<4?'clipping':'notice';
 return {kind,tag:sc.tag,title,body:state.screen==='bulletin'?'The report records what happened. The next decision is still yours.':state.screen==='outcome'?'The statement is made. The work it requires continues.':sc.question,stamp:state.screen==='bulletin'?'Update received':state.screen==='outcome'?'For the record':'Response awaited',caption:state.occupation?'The crowd is still here. Someone must answer.':'The political year continues beyond the original moment.'};
}
function dossier(){const d=documentData();const sum=(state.cash/100000).toFixed(1);return `<aside class="dossier-rail ${d.kind==='assurance'?'assurance':''}"><div class="rail-label"><span>On your desk</span><span>${String(state.turn+1).padStart(2,'0')} / 12</span></div><div class="document ${d.kind}">${['night','clipping'].includes(d.kind)?'<div class="field-photo" role="img" aria-label="Fictional student protest scene"></div>':''}<div class="document-top"><span>${d.tag}</span><span>CJP</span></div>${d.kind==='assurance'?'<div class="seal" aria-hidden="true">§</div>':''}<h3>${d.title}</h3>${d.kind==='ledger'?`<div class="ledger-sum">₹${sum} <small style="font-size:20px">lakh</small></div><div class="ledger-row"><span>Available balance</span><span>Accounts desk</span></div>${state.screen==='mini'?'<div class="ledger-row"><span>Current runway</span><span>Seven weeks</span></div>':''}`:''}<p>${d.body}</p>${d.kind==='register'?'<div class="micro-grid"><span>District / school</span><span>Report / status</span><span>Verification</span><span>Follow-up</span></div>':'<div class="document-rule"></div><div class="document-lines" aria-hidden="true"></div>'}<div class="stamp">${d.stamp}</div>${d.kind==='assurance'?'<div class="signature">For the record</div>':''}</div><p class="rail-caption">${d.caption}</p></aside>`;}
function institutionalPortrait(){const d=movementDiagnosis(calculateEnding()),f=state.flags;const items=[f.has('MEMBERSHIP_GOVERNANCE')?'Membership & decisions':'Founders & representatives',f.has('EVIDENCE_CAPACITY')?'Evidence & case records':'Campaigns & correspondence',f.has('COALITION_CAPACITY')?'Coalition relationships':'Public constituency'];return `<aside class="institution-portrait portrait-${d.state.toLowerCase()}" aria-label="Institutional record after one year"><div class="portrait-kicker">What the year leaves behind</div>${items.map((x,i)=>`<div class="file-spine">0${i+1} &nbsp; ${x}</div>`).join('')}<p class="portrait-footer">${{THRIVED:'An institution beyond the moment.',RELEVANT:'A voice with work still to do.',SURVIVED:'The name remains. The space has moved.',ABSORBED:'The records travel. The ownership changes.'}[d.state]}</p></aside>`;}
const renderBeforeArt=render;
render=function(){
 document.body.dataset.screen=state.screen;
 document.body.classList.toggle('late-year',state.turn>=8);
 renderBeforeArt();
 if(state.screen==='title')return;
 app.insertAdjacentHTML('afterbegin',masthead(state.screen==='ending'?'The year in review':`Year one / ${String(state.turn+1).padStart(2,'0')}`));
 if(state.screen!=='ending'){
 const track=`<nav class="year-strip" aria-label="Political year: turn ${state.turn+1} of 12"><span class="year-label">The political year</span><div class="year-track" aria-hidden="true">${TURNS.map((_,i)=>`<span class="${i<state.turn?'past':i===state.turn?'now':''}"></span>`).join('')}</div><span class="year-end">The election approaches</span></nav>`;
 app.querySelector('.masthead').insertAdjacentHTML('afterend',track);
 const screen=app.querySelector('.screen');const content=screen.innerHTML;screen.innerHTML=dossier()+`<main class="reading-column">${content}</main>`;
 
 }else{
 const screen=app.querySelector('.ending-screen');const intro=document.createElement('section');intro.className='ending-lead';const text=document.createElement('div');text.className='ending-summary';for(const selector of ['.ending-state','.ending-state-value','.ending-future','.ending-diagnosis'])text.append(screen.querySelector(selector));intro.append(text);intro.insertAdjacentHTML('beforeend',institutionalPortrait());screen.prepend(intro);
 }
};
