// Work persists between editions. Deadlines are calendar-based, never real-time.
const resetBeforePressure=resetGame;
resetGame=function(seed){resetBeforePressure(seed);state.pressure={jobs:[],nextId:1,assigned:[],log:[]};};
function ensurePressure(){return state.pressure||(state.pressure={jobs:[],nextId:1,assigned:[],log:[]});}
function addCommitment(key,title,person,request,days,kind){const p=ensurePressure();if(p.jobs.some(j=>j.key===key))return;p.jobs.push({id:p.nextId++,key,title,person,request,due:edition()[2]+days,kind,status:'open',misses:0});}
function deadlineName(day){const date=new Date(Date.UTC(2025,0,day));return date.toLocaleDateString('en-GB',{day:'numeric',month:'long',timeZone:'UTC'});}
function pressurePublicState(){const p=ensurePressure();return {teams:2,assigned:p.assigned.length,jobs:p.jobs.filter(j=>j.status==='open').map(j=>({id:j.id,title:j.title,from:j.person,request:j.request,due:deadlineName(j.due),assigned:p.assigned.includes(j.id)})),latest:p.log.slice(-2)};}
function pressurePanel(){const p=pressurePublicState();if(!p.jobs.length&&!p.latest.length)return '';return `<section class="pressure-desk"><div class="pressure-heading"><span>Movement desk · ${edition()[0]}</span><strong>${2-p.assigned} of 2 teams available</strong></div><p class="pressure-intro">Assign a team before making your political decision. Unassigned work carries forward. Missed deadlines can send people elsewhere; time advances with the next edition.</p>${p.jobs.map(j=>`<div class="pressure-job"><div><span class="pressure-source">${j.from} · Due ${j.due}</span><h3>${j.title}</h3><p>${j.request}</p></div><button class="team-button ${j.assigned?'assigned':''}" aria-pressed="${j.assigned}" onclick="assignTeam(${j.id})" ${!j.assigned&&p.assigned>=2?'disabled':''}>${j.assigned?'Release team':'Assign team'}</button></div>`).join('')}${p.latest.length?`<details class="pressure-record"><summary>Latest reports from your teams</summary>${p.latest.map(x=>'<p>'+x+'</p>').join('')}</details>`:''}</section>`;}
function assignTeam(id){if(state.screen!=='turn')return;const p=ensurePressure(),j=p.jobs.find(j=>j.id===id&&j.status==='open');if(!j)return;const at=p.assigned.indexOf(id);if(at>=0)p.assigned.splice(at,1);else if(p.assigned.length<2)p.assigned.push(id);render();}
function jobQuality(j){if(j.kind==='legal')return legal()&&state.vars.org+state.vars.acc>=90;if(j.kind==='chapter')return has('BUILT_CHAPTERS')&&state.vars.org>=50;if(j.kind==='evidence')return has('EVIDENCE_CAPACITY')&&state.vars.acc>=45;if(j.kind==='alliance')return allied();return false;}
function resolvePressure(){const p=ensurePressure(),reports=[];for(const id of p.assigned){const j=p.jobs.find(j=>j.id===id&&j.status==='open');if(!j)continue;if(jobQuality(j)){j.status='done';change({ownership:2,rel:1});reports.push(j.person+': '+({legal:'The team has prepared the hearing file and confirmed representation. The family no longer has to chase the founders.',chapter:'Local organisers settle the rota and keep the committee working.',evidence:'The checked record is ready. Consent and disputed entries have been resolved.',alliance:'The delegates agree who will do the work and record the shared commitments.'}[j.kind]));}else{j.progress=(j.progress||0)+1;if(j.progress>=2){j.status='done';reports.push(j.person+': The team completes the follow-up after two rounds of work. It took personal effort that a permanent service could have saved.');change({acc:2});}else{const next=Math.min(11,state.turn+(state.turn===1&&state.widened?2:1));const nextDay=(state.branch==='leave'&&LEAVE_EDITIONS[next]||EDITIONS[next])[2];j.due=Math.max(j.due,nextDay+7);reports.push(j.person+': A team made contact and secured more time. The underlying work is still unfinished; we need another assignment.');}}}p.assigned=[];p.log.push(...reports);return reports;}
function expirePressure(){const p=ensurePressure(),reports=[];for(const j of p.jobs.filter(j=>j.status==='open'&&j.due<edition()[2])){j.misses++;change({ownership:-3,acc:-2});if(j.misses>=2){j.status='transferred';change({partyDependence:j.kind==='legal'?5:0});reports.push(j.person+': '+j.title+' has been taken to another organisation. They have agreed to take over the follow-up.');}else{j.due=edition()[2]+25;reports.push(j.person+': The deadline passed without support. We are still waiting, but have begun asking other organisations.');}}p.log.push(...reports);}
function seedPressure(){if(state.turn===2&&state.branch==='leave'){
 addCommitment('case','Prepare the student hearing file','Asha · student representative','“The case is still listed. Who will help me prepare?”',20,'legal');
 addCommitment('partners','Confirm the shared support rota','Imran · coalition delegate','“We offered volunteers. We still need a named coordinator.”',24,'alliance');
 addCommitment('records','Check names before publishing updates','Meera · case desk','“Two entries conflict. Please give us time to verify them.”',18,'legal');
 }
 if(state.turn===4){addCommitment('schools','Verify the first school reports','Meera · research coordinator','“Families want an answer. Some photographs have no date or location.”',25,'evidence');addCommitment('local','Support a parents’ organising meeting','Dev · local organiser','“People will come on Sunday. We need someone to help turn it into continuing work.”',28,'chapter');}
 if(state.turn===6)addCommitment('mandate','Keep partners inside the new programme','Imran · coalition delegate','“Your new statement includes work nobody asked us to take on.”',23,'alliance');
 if(state.turn===10)addCommitment('protection','Arrange continuing support for the family','Asha · student representative','“Whatever happens at the station, someone needs to follow the case afterward.”',24,'legal');
}
const selectBeforePressure=applySelection;
applySelection=function(i,mini=false){if(!mini&&state.screen==='turn'){const c=activeScene().choices[i];if(!c||(c.need&&!c.need()))return;const reports=resolvePressure();selectBeforePressure(i,mini);if(reports.length&&state.lastChoice){state.lastChoice.text+=' '+reports.join(' ');const h=state.history[state.history.length-1];if(h)h.consequence+=' '+reports.join(' ');render();}}else selectBeforePressure(i,mini);};
const nextBeforePressure=nextTurn;
nextTurn=function(){const previous=state.turn;nextBeforePressure();if(state.turn!==previous&&state.screen==='turn'){expirePressure();seedPressure();render();}};
