// Revised political year. Scores and event weights are internal only.
const app=document.getElementById('app');
const clamp=n=>Math.max(0,Math.min(100,n));
const state={};
const SPACE=[85,89,90,90,92,92,94,94,96,97,98,100];
const choice=(id,label,desc,out,effect={},extra={})=>({id,label,desc,out,effect,...extra});
const scene=(event,report,question,choices,tag='FROM THE GROUND')=>({event,report,question,choices,tag});
const has=f=>state.flags.has(f);
const capable=k=>has(k);
const allied=()=>state.structure!=='open'&&state.trust>=55&&has('COALITION_CAPACITY')&&!has('SEVERE_ALLIANCE_RUPTURE');
const legal=()=>has('BUILT_LEGAL_INFRASTRUCTURE');
const members=()=>state.governance==='membership';
const council=()=>state.governance==='council'&&allied();
const cashUsable=()=>state.funding!=='grant'&&state.cash>=150000;
function resetGame(seed){
 const n=typeof seed==='number'?seed>>>0:crypto.getRandomValues(new Uint32Array(1))[0];
 Object.assign(state,{vars:{rel:80,org:30,agn:55,ind:75,acc:30,mob:75},leg:72,breadth:75,perceived:72,trust:55,leader:45,leverage:20,dependency:0,allianceDependency:0,absorptionBonus:0,allianceState:"INFORMAL",scars:[],tags:[],mobilisationUses:1,access:0,staff:true,space:85,flags:new Set(['COALITION_CAPACITY']),turn:0,history:[],events:[],screen:'title',lastChoice:null,assurance:null,funding:null,cash:470000,burn:470000/7,structure:null,governance:null,charter:null,participants:null,mandate:'unsettled',pending:[],queue:[],mini:null,branch:null,widened:false,occupation:false,bulletin:null,proxyDebt:0,streetCalls:0,seed:n,rng:n,financeNote:'',govtNote:'',futurePull:{party:0,lobby:0,social:0,absorption:0},fundingRestricted:false});
 render();window.scrollTo(0,0);
}
function random(){state.rng=(Math.imul(1664525,state.rng)+1013904223)>>>0;return state.rng/4294967296;}
function change(e={}){for(const [k,v] of Object.entries(e)){if(k in state.vars)state.vars[k]=clamp(state.vars[k]+v);else if(['leg','breadth','perceived','trust','access','leader','leverage','dependency','allianceDependency','absorptionBonus'].includes(k))state[k]=k==='access'?Math.max(0,Math.min(3,state[k]+v)):clamp(state[k]+v);}}
function completeStructure(){
 if(state.governance===state.structure&&state.governance)return;
 if(state.structure==='membership'){state.governance='membership';state.flags.add('MEMBERSHIP_GOVERNANCE');state.flags.add('BUILT_CHAPTERS');change({org:9,acc:9});}
 else if(state.structure==='council'&&allied()){state.governance='council';change({org:7,acc:5});}
 else if(state.structure==='federated'){state.governance='federated';state.flags.add('BUILT_CHAPTERS');change({org:7});}
 else if(state.structure==='central'){state.governance='central';}
 state.mandate=state.governance?'ratified':'unsettled';
}
function servicePending(flag){if(!has(flag)&&!state.pending.some(p=>p.flag===flag))state.pending.push({flag,due:state.turn+1});}
const TURNS=[
scene('They Say You Won',()=> '“The resignation has brought more students onto the streets. Groups are still arriving, and new demands are being raised. But police are turning back food deliveries, restricting nearby transport and stopping new arrivals after dusk. Officers have been filming students and recording names and colleges. A senior official has offered talks—if the tents come down first. The crowd is waiting for the organisers’ response.”','What do you tell them?',[
choice('a','“We won. Bring the tents down.”','End the protest and pursue the remaining commitments.','Students begin packing. Your negotiators call before the last tents come down: what assurance can they accept on your behalf?',{mob:-16,leg:5},{set:()=>{state.branch='leave';state.occupation=false;state.flags.add('ENDED_PROTEST');state.queue.push('assurance');},pull:'social'}),
choice('b','“We leave when the settlement is complete.”','Name the outstanding commitments and ask the crowd to stay.','You read out the unfinished commitments. Volunteers return to the food rota. The official asks for a written exit condition; the police restrictions remain.',{mob:5,org:2},{set:()=>{state.branch='stay';state.occupation=true;state.flags.add('CLEAR_SETTLEMENT');},pull:'lobby'}),
choice('c','“This is bigger than a resignation.”','Ask the crowd to stay for the next fight.','The call is cheered. Representatives make their way to the stage. They want to know what tomorrow’s demands will be.',{mob:7,agn:-5},{set:()=>{state.branch='stay';state.occupation=true;state.queue.push('charter','participants','structure','dispute');},pull:'party'}),
choice('d','“The groups who built this decide together.”','Call the alliance into an overnight meeting.','The camp stays for the meeting. Partners arrive with different instructions from their organisations. Staying tonight is not yet consent to an indefinite protest.',{trust:8,org:3},{set:()=>{state.branch='stay';state.occupation=true;state.participants='existing';},pull:'lobby'})]),
null,null,null,
scene('Build Something Between the Protests',()=> '“School photographs are arriving from across the country: damaged rooms, missing facilities, unanswered complaints. Parents who never joined the protest are sending material. Your team has opened another folder. It is already filling faster than anyone can read it.” '+(state.branch==='leave'?'After dispersal, this is a way for volunteers to work together again.':'After the protest, families want to see what the movement can do beyond holding a street.'),'What happens after somebody sends a report?',[
choice('a','Publish a weekly collection of verified stories.','Put the reports and families’ accounts into public view.','The first collection travels widely. Families begin asking when someone will visit. Your editors must explain what publication can—and cannot—promise.',{rel:10,leg:3},{pull:'social'}),
choice('b','Build a district evidence register.','Check submissions and maintain a public record without exposing private case details.','Researchers begin checking the first district. Most submissions are still waiting. Someone must keep the records current after the campaign stops trending.',{org:7,acc:6,agn:4},{set:()=>servicePending('EVIDENCE_CAPACITY'),pull:'lobby'}),
choice('c','Help parents form local committees.','Give families a way to organise and follow problems together.','Parents arrange their first meetings. Local coordinators need training and a way to decide which complaints come first.',{org:8,mob:7,breadth:5},{set:()=>{state.flags.add('BUILT_CHAPTERS');if(!state.structure)state.queue.push('structure','dispute');},pull:'party'}),
choice('d','Follow selected cases through to repair.','Assign caseworkers to a few schools and pursue the responsible offices.','Caseworkers and a small lawyer team begin with selected schools. Offices ask for documents; families wait for visits. Taking on fewer cases means saying no to many others.',{org:6,leg:7,access:1},{set:()=>{servicePending('SERVICE_CAPACITY');servicePending('BUILT_LEGAL_INFRASTRUCTURE');},pull:'lobby'})],'REPORT · SCHOOL THEEK KARO'),
scene('They Give You a New Name',()=> '“A hostile label is spreading through television clips and messaging groups. An irreverent student identity is being recast as an accusation of anti-state politics. Your most committed supporters want to reclaim it. Parents are calling local organisers to ask what their children have joined.” '+(state.branch==='stay'?'Clips of the extended protest are being replayed.':'Reports from the school campaign are circulating alongside the accusation.'),'What do you say—and what do you ask people to do?',[
choice('a','Reclaim the label at a public meeting.','Ask supporters to stand together rather than retreat.','The room is loud and determined. Outside it, organisers must answer quieter messages from students who no longer feel comfortable being named.',{mob:8,breadth:-8},{pull:'social'}),
choice('b','Issue a factual rebuttal and disclose affiliations.','Explain who funds the work and who makes decisions.','You publish the affiliations and funding arrangements. Some people welcome the record. Others circulate the connections they find most suspicious.',{perceived:5,acc:5},{set:()=>state.flags.add('PUBLIC_RULES'),pull:'lobby'}),
choice('c','Keep the next campaign on school outcomes.','Invite people to take part in practical work.','The next report concerns school repairs. Parents share it. Students being personally targeted still ask who will stand beside them.',{leg:4,breadth:4,mob:-3},{pull:'lobby'}),
choice('d','State an explicit democratic-rights position.','Explain what the movement believes about dissent and institutional power.','The statement gives your organisers a clearer argument. Some supporters embrace it; others say this is more than they originally joined.',{agn:8,breadth:-6},{set:()=>state.flags.add('RIGHTS_POSITION'),pull:'party'})],'REPORT · THE NAME IS TRAVELLING'),
scene('The Issues Have Changed',()=> '“The messages are no longer just about education. Organisers want responses on recruitment, housing, discrimination and public accountability. Some need a repaired classroom. Others ask who is responsible for a pattern. Your allies do not agree on every answer.” '+(state.charter?`Your earlier promise concerned ${charterName()}.`:'The original education campaign remains your most familiar claim.'),'Which claims will you take responsibility for?',[
choice('a','Keep education as the mandate.','Concentrate the team on the field it knows.',()=> 'You refer other cases onward. '+(has('WIDENED_TO_YOUTH')?'Organisers quote your earlier youth promise back to you. Narrowing now needs an explanation.':'People know which requests your team can take, though others find different leaders.'),{agn:7,rel:-5},{set:()=>{if(has('WIDENED_TO_YOUTH'))change({acc:-8,leg:-5});},pull:'lobby'}),
choice('b','Adopt a wider youth programme.','Take responsibility for a defined set of issues affecting young people.','New organisers volunteer. Your representatives now need positions they can defend on housing, employment and discrimination.',{agn:3,rel:6,org:-4},{set:()=>{if(members()||council()){state.queue.push('agenda');}else {state.charter='youth';state.flags.add('WIDENED_TO_YOUTH');}},pull:'party'}),
choice('c','Form issue-specific alliances.','Work with groups that already know each issue.','You approach housing and labour organisers. They want shared decisions and reciprocal help, not just a place on a poster.',{trust:8,org:4,ind:-3},{set:()=>state.flags.add('COALITION_CAPACITY'),pull:'lobby'}),
choice('d','Respond campaign by campaign.','Let urgent requests guide the next action.','Statements go out quickly. Volunteers begin asking which commitments will still matter next month.',{rel:6,agn:-10},{pull:'social'})],'REPORT · REQUESTS FROM THE CHAPTERS'),
scene('Whose Movement?',()=> '“'+({central:'Your appointed spokesperson has issued a disputed statement.',federated:'A regional unit has issued a disputed statement.',membership:'An elected representative has issued a disputed statement.',council:'An alliance partner has issued a disputed statement.',open:'An autonomous group using your name has issued a disputed statement.'}[state.structure]||'A volunteer using your name has issued a disputed statement.')+' Some organisers want it withdrawn. Others say withdrawal would betray the people affected. The press is asking which position represents the movement.” '+(state.mandate==='breached'?'Partners remember the night leadership spoke without agreement.':''),'Who has the authority to settle this?',[
choice('a','Have the founders issue an interim position.','Give an answer now and state its limits.','The founders issue a position. Those who expected a shared decision demand a review.',{acc:-5,org:2},{set:()=>{if(members()||council())change({trust:-8,leg:-4});},pull:'party'}),
choice('b','Use the elected body’s agreed procedure.','Ask representatives to hear the complaint and decide.','The hearing is scheduled. Founders must wait with everyone else, and accept that the decision may go against them.',{acc:8,org:4},{need:members,why:'There is no elected body with an agreed mandate.',pull:'lobby'}),
choice('c','Refer it to the alliance council.','Ask mandated partners to settle the joint position.','Delegates take instructions back to their organisations. A joint answer takes longer than a statement from the stage.',{trust:6,acc:5,ind:-3},{need:council,why:'There is no functioning council trusted to speak for the alliance.',pull:'lobby'}),
choice('d','Open a time-limited public consultation.','Hear participants before publishing an interim answer.','Responses arrive in waves. You have opinions, not a verified electorate. Somebody still has to take responsibility for the final answer.',{rel:3,org:-4},{pull:'social'})],'INTERNAL · A STATEMENT IN YOUR NAME'),
scene('Come Inside',()=> '“The ministry wants the movement’s proposals. Several allies are not invited. Officials want a photograph after the meeting; your members want to know what you will be authorised to agree.” '+(state.trust<35?'Some former partners have stopped returning your calls.':''),'What are your terms for entering?',[
choice('a','Decline and publish your demands outside.','Keep your distance from the consultation.','The meeting goes ahead with other groups. Your statement circulates outside; you are not there to argue over the wording.',{ind:5,access:-3},{pull:'social'}),
choice('b','Attend through a private delegation.','Use the meeting for detailed negotiation.','Officials speak candidly. Your members receive no independently checkable record, and the photograph travels faster than your explanation.',{access:2,acc:-6,perceived:-5},{pull:'absorption'}),
choice('c','Publish your mandate and an attributed meeting record.','Make your proposals and account of the meeting inspectable.','You publish the record and ask officials to correct any disputed attribution. The public can follow the exchange, but the ministry may not welcome it.',{acc:7,access:1},{set:()=>state.flags.add('TRANSPARENT_ACCESS'),pull:'lobby'}),
choice('d','Attend under an agreed alliance mandate.','Take a joint position into the room.','Delegates enter with instructions. On disputed concessions, they must return to the organisations that sent them.',{access:1,trust:5,ind:-3},{need:council,why:'No agreed alliance mandate is available for this meeting.',pull:'lobby'})],'DEVELOPING · AN OFFICIAL INVITATION'),
scene('Everyone Has Learnt',()=> '“Party organisers now arrive with lawyers and elected representatives. Some of your demands appear in their programmes; others have become Government announcements. Students who once messaged you are taking cases elsewhere. Volunteers ask what next year’s work is for.”','What should people still come to you for?',[
choice('a','The ability to bring people together in public.','Put the next effort into collective pressure.',()=>state.vars.mob>50?'Local organisers begin calling participants. A public action still needs transport, safety and a reason to come.':'The call goes out, but several local groups are quiet. An audience is not the same as people who can come tomorrow.',{mob:3,rel:3},{set:()=>{if(state.vars.mob<40)change({leg:-5});},pull:'social'}),
choice('b','Evidence and a charter that tests every party.','Publish a standard against which their promises can be judged.',()=>has('EVIDENCE_CAPACITY')?'Your records support the charter. Parties contest the weights; some members dispute the rankings.':'Without maintained records, you publish a limited draft. Several claims need checking before you can score anyone.',{agn:5,org:-3},{set:()=>{state.flags.add('SCORECARD');if(has('EVIDENCE_CAPACITY'))change({rel:4});else change({leg:-3});change({access:-1});},pull:'lobby'}),
choice('c','A local network that follows problems through.','Keep people working on cases between crises.',()=>has('SERVICE_CAPACITY')||has('BUILT_CHAPTERS')?'Coordinators take on the next set of cases. Slow follow-up keeps tying up time and money.':'You begin with a small pilot. There is no local network to activate at national scale yet.',{org:4,rel:-3},{pull:'lobby'}),
choice('d','An independent route into political representation.','Begin conversations about candidates and a collective programme.','Supporters ask which seats and who will stand. Questions about money, candidate selection and policy can no longer wait.',{agn:4,ind:2,mob:-3},{set:()=>state.flags.add('ELECTORAL_INTENT'),pull:'party'})],'REPORT · THE COMPETITION FOR YOUTH'),
scene('Your People Need You',()=> '“Members have been attacked. Their families are at the police station, where an FIR has not yet been registered. They need protection now. Your local organiser has sent one message: who can you get here?”','What can you put into motion today?',[
choice('a','Activate your legal response.','Send the lawyer team with the case documents.','The team takes statements with consent and submits the complaint. Representation is in place; registration and protection still require an institutional response.',{acc:7,org:3},{need:legal,why:'You have no staffed lawyer team maintaining the case files.',pull:'lobby'}),
choice('b','Activate the alliance’s collective response.','Ask partners to bring lawyers, contacts and people.','Partners arrange a collective intervention. Families see who comes, and your organisation owes the same support when partners call.',{trust:4,ind:-4,acc:5},{need:allied,why:'The relationships needed for a collective response have not been sustained.',pull:'absorption'}),
choice('c','Escalate through an institutional contact.','Reach the office that can intervene.','Your contact takes the details. An acknowledgement is not yet protection; the families remain at the station.',{acc:4,ind:-2},{need:()=>state.access>0,why:'There is no functioning institutional channel to call.',pull:'lobby'}),
choice('d','Mobilise outside the police station.','Bring a public presence behind the families.','Local organisers gather supporters. They must keep people safe while pressing for registration of the complaint.',{mob:-6,rel:5},{need:()=>state.vars.mob>=30&&state.breadth>=20,why:'Your local organisers cannot currently gather a safe, credible public action.',pull:'social'}),
choice('e','Stay with the families and seek emergency outside help.','Call new lawyers and organisations, one by one.','You remain with the families while asking for introductions. A new lawyer offers an initial call. Help is slower because the relationships were not there.',{rel:-5,ind:-5,acc:-3},{pull:'absorption'})],'URGENT · AFTER THE RALLY'),
scene('Elections Organise the Space',()=> '“Parties are approaching your organisers. Some want endorsements; others offer individual roles. Your demands are circulating in campaign speeches. Supporters ask whether the movement will stand, bargain or stay outside. Several leaders want an answer before responding to offers.”','What will you commit the movement to?',[
choice('a','Field independent candidates in selected seats.','Put a collective organisation behind a small slate.','Candidate selection begins under your existing rules. The campaign draws people and money away from other work. Announcing a slate is only the beginning.',{mob:-3,ind:2},{need:()=>state.vars.org>=55&&state.vars.mob>=45&&state.vars.agn>=45&&state.vars.ind>=55&&cashUsable(),why:'The organisers, programme, independent funds and reachable supporters for a slate are not all in place.',set:()=>{state.flags.add('ANNOUNCED_CANDIDATES');state.cash-=150000;},pull:'party'}),
choice('b','Seek public commitments from every political formation.','Put the same demands to each party.','Parties respond unevenly. Some accept language, others ask for an endorsement. Your team records the differences and prepares to follow the promises.',{agn:3,acc:2},{need:()=>has('EVIDENCE_CAPACITY')&&state.leg>=40&&state.vars.ind>=40,why:'You lack the maintained evidence, credibility or autonomy to bargain across parties on these terms.',pull:'lobby'}),
choice('c','Campaign on issues without endorsements.','Keep participation open across voting choices.','Some supporters stay with the issue campaign. Others want a clearer electoral answer. Parties continue borrowing language you do not control.',{rel:2},{need:()=>state.vars.rel>=30&&state.leg>=25&&(state.vars.mob>=25||state.breadth>=35),why:'There is too little public reach or participation to sustain that campaign now.',pull:'social'}),
choice('d','Permit individual electoral choices under the existing rules.','Let people respond to offers without a collective endorsement.',()=>members()||council()?'Individuals may accept offers, but the name and assets remain under collective rules. Departures still take experience with them.':'Leaders open separate conversations. Without shared rules, it is unclear which contacts, language and resources they may take.',{ind:-3},{set:()=>state.flags.add('INDIVIDUAL_DEALS'),pull:'absorption'})],'REPORT · BEFORE THE ELECTION')];
const LEAVE=[
scene('The Protest Ends. The Protests Don’t.','“The tents are gone, but their example is travelling. Students protesting fees, examinations and recruitment are citing the resignation as proof that pressure works. Your inbox is filling with requests for lawyers, publicity and organisers. Your volunteers are back in class.”','What do you build for the people approaching you?',[
choice('a','Give other struggles your platform.','Put overlooked student cases into public view.','Requests arrive faster than you can verify them. Other organisers welcome the coverage but still need people who can follow cases.',{rel:8,org:-2},{pull:'social'}),
choice('b','Set up a protest-support desk.','Coordinate the lawyers and organisers offering help.','A rota begins with a small intake. Volunteers need consent procedures, training and someone who decides which cases the desk can handle.',{org:6,acc:4},{set:()=>{state.flags.add('SUPPORT_DESK');state.queue.push('structure','dispute');},pull:'lobby'}),
choice('c','Build an education working group.','Concentrate volunteers around the original mandate.','A smaller group begins reviewing education issues. Wider youth campaigns find help elsewhere. Your volunteers need a way to make decisions.',{agn:6,leg:3,rel:-5},{set:()=>state.queue.push('structure','dispute'),pull:'lobby'}),
choice('d','Keep the original alliance working.','Invite the protest’s partners into a continuing network.','Partners agree to discuss joint work. Their organisations expect more than requests for help whenever a crisis returns.',{trust:8,org:4,perceived:-3},{set:()=>{state.participants='existing';state.queue.push('structure','dispute');},pull:'lobby'})],'REPORT · CAMPUSES ACROSS THE COUNTRY'),
scene('The Promise Comes Due',()=> '“Six weeks have passed. Students say the original cases remain open. Some report online targeting and worry about police records made at the site. Their messages now ask: who is following this up?” '+({written:'Your file contains a signed commitment from the responsible authority.',minister:'The minister’s public assurance is recorded; an operative instruction is still missing.',intermediary:'The intermediary remembers a private understanding and asks not to be named.',resignation:'No case-withdrawal agreement was secured. You must seek one now, not allege that one was broken.'}[state.assurance]||'The remaining settlement has no clear public record.'),'How do you get the cases moving now that the crowd is gone?',[
choice('a','Announce a date to return to the streets.','Give the responsible office a public deadline.','The date brings an initial response from the office. Some files begin moving, but organisers must now establish who would actually return.',{mob:3,acc:2},{pull:'social'}),
choice('b','Assign a legal team and build a case tracker.','Keep sensitive details private; publish only consented, verified progress.',()=>has('SUPPORT_DESK')?'The existing intake helps lawyers assemble the first files. The office begins reviewing them. Other cases still need verification.':'Lawyers begin reconstructing the record from scattered messages. Some cases reach the office; the rest wait while the team establishes a reliable register.',{org:7,acc:7,mob:-3},{set:()=>{servicePending('BUILT_LEGAL_INFRASTRUCTURE');if(state.assurance==='written')change({acc:3});},pull:'lobby'}),
choice('c','Ask partners and political contacts to intervene.','Seek introductions to people who can move the cases.',()=>allied()?'Partners bring lawyers and elected representatives. Some cases move. Students can see which organisations delivered the intervention.':'You ask for new introductions. Calls take days; a partner eventually offers to raise a few cases, without promising a continuing service.',{ind:-7,perceived:-5,acc:4},{set:()=>{state.flags.add('OPPOSITION_COLLABORATION');change({trust:3});},pull:'absorption'}),
choice('d','Send a delegation to the responsible office.','Seek a direct follow-up channel.','The office begins processing some files and asks for a single point of contact. Observers offer different explanations for its willingness to talk; none is established.',{access:1,acc:2,perceived:-3},{pull:'lobby'})],'FOLLOW-UP · SIX WEEKS LATER'),
scene('Somebody Else Gets There First','“Local organisers were here before your team. Lawyers have secured a hearing, and elected representatives are pressing for detained students’ release. The crowd knows who turned up. Your supporters are asking whether you are coming.”','What do you bring that is not already here?',[
choice('a','Call a national mobilisation behind the students.','Ask local organisers to coordinate a wider action.','You offer a national call. Local leaders want the action to support their plan, not replace it. Your team takes on another set of logistics.',{rel:5,mob:-4,org:-2},{pull:'party'}),
choice('b','Join the existing coordination team.','Work under the plan already taking shape.','You share work, decisions and the stage. Party-affiliated partners are now visibly part of the response.',{org:5,trust:8,ind:-5,perceived:-3},{set:()=>state.flags.add('COALITION_CAPACITY'),pull:'absorption'}),
choice('c','Offer verified publicity and practical support.','Ask what is missing and supply that.','Local organisers ask for a specific piece of help. You deliver it. The camera remains on the people who were there first.',{leg:4,trust:4,rel:-3},{pull:'lobby'}),
choice('d','Keep your team on its existing programme.','Protect commitments already made.',()=> 'The crisis moves without you. '+(has('WIDENED_TO_YOUTH')?'Students quote your wider promise and ask why it did not include them.':'Your volunteers finish work that would otherwise have been abandoned.'),{agn:4,rel:-8},{set:()=>{if(has('WIDENED_TO_YOUTH'))change({acc:-7});},pull:'social'})],'LIVE · OUTSIDE ANOTHER CAMPUS')];
const STAY=[
scene('Day Five: “You Already Won”',()=> '“The crowd remains large. Ministers say the organisers refuse to accept victory. Television crews are asking commuters about disruption. Inside the barricades, volunteers are rationing supplies. Some allies say they agreed to a protest, not an indefinite protest.” '+(state.charter?`The next programme concerns ${charterName()}.`:''),'What justifies asking people to stay?',[
choice('a','Publish unfinished commitments and an exit timetable.','Keep continued pressure tied to a specific settlement.','Reporters have a list to check. Volunteers know what would end the protest. Those who came for a wider programme ask what happens to it.',{agn:5,mob:-3},{set:()=>{state.flags.add('CLEAR_SETTLEMENT');if(state.charter&&state.charter!=='education')change({acc:-3});},pull:'lobby'}),
choice('b','Put a second charter to the camp.','Set out the next fight and ask people to support it.',()=>state.charter?'The proposed charter returns to the people who must carry it. It cannot be changed simply because the stage wants a new line.':'The crowd wants to hear more. Representatives immediately ask what the new programme is and who gets to decide.',{mob:4,agn:-3},{set:()=>{if(!state.charter)state.queue.push('charter','participants','structure','dispute');else state.queue.push('agenda');},pull:'party'}),
choice('c','Let participating organisations negotiate the demands.','Give partners a say in what they are sustaining.','The organisations send representatives. Several need to consult their members before agreeing. You cannot promise a joint charter tonight.',{trust:6,org:3,mob:-3},{set:()=>{state.participants='existing';if(!state.structure)state.queue.push('structure','dispute');},pull:'lobby'}),
choice('d','Hold another public assembly.','Demonstrate that the protest still has support.','The assembly fills the road. Food, sanitation and protection become more urgent. An impressive crowd has not answered the exit question.',{mob:7,leg:-3,breadth:-3},{pull:'social'})],'LIVE · THE PROTEST'),
scene('Who Speaks for This Crowd?',()=> '“The stage has announced one position; participating groups have issued another. The kitchen team needs to know how long supplies must last. Police want a named liaison.” '+(state.structure?`You proposed ${structureName()}. People now want to see it work.`:'There is still no agreed way to authorise a decision.'),'What will you put in place today?',[
choice('a','Complete the procedure you promised.','Finish the appointments, roll or delegate mandates.',()=>state.structure&&state.structure!=='open'?'The team finishes the work needed to authorise decisions. It consumes a day at the camp, but the next delegation can name who sent it.':'You gather the groups to agree how decisions will work. They cannot simply be told that a procedure already exists.',{mob:-5,org:2},{set:()=>{if(state.structure&&state.structure!=='open')completeStructure();else state.queue.push('structure','dispute');},pull:'lobby'}),
choice('b','Give the founders an interim mandate.','State its limits and a date for review.','The founders can answer urgent requests. Those promised a shared process expect the review to happen.',{org:4,acc:-3},{set:()=>{state.mandate='interim';if(!state.structure)state.structure='central';},pull:'party'}),
choice('c','Require partners’ agreement on common statements.','Publish only the points they authorise.','Statements get shorter. Partners retain a say, but their organisations take time to return instructions.',{trust:5,acc:3,mob:-3},{set:()=>{if(allied()){state.structure='council';state.governance='council';state.mandate='ratified';}},pull:'lobby'}),
choice('d','Let each group speak for itself.','Keep the platform open and name statements as local.','Several positions reach journalists. The energy continues, but nobody can promise that a settlement binds everyone.',{mob:4,agn:-7,org:-4},{set:()=>{state.structure='open';state.governance=null;state.mandate='unsettled';state.flags.delete('MEMBERSHIP_GOVERNANCE');},pull:'social'})],'REPORT · INSIDE THE CAMP'),
scene('Separate Invitations',()=> '“The Government has invited selected representatives to talks. Some groups keeping the camp supplied are excluded. Officials distinguish between ‘students’ and ‘political elements’. Your partners want to know whether you will enter without them.”','On whose mandate do you negotiate?',[
choice('a','Send CJP’s leadership alone.','Take the invitation and report back.','Your delegation reaches the room. Excluded partners say they were useful for the protest but not the settlement. Some withdraw their support.',{access:1,trust:-22,ind:2},{set:()=>{state.mandate='breached';state.flags.add('EXCLUDED_ALLIES');},pull:'absorption'}),
choice('b','Insist on including every participating organisation.','Defend their place at the table.','Talks stall while the list is disputed. Partners stay beside you, but the camp cannot wait indefinitely.',{trust:7,mob:-7,org:-3},{pull:'lobby'}),
choice('c','Send a jointly mandated delegation.','Let a small team negotiate on agreed instructions.','Delegates enter with a mandate and bring disputed terms back for approval. The negotiation takes longer than a private agreement.',{acc:6,access:1,trust:3},{need:()=>council()||members(),why:'No elected assembly or functioning council has authorised a joint delegation.',pull:'lobby'}),
choice('d','Refuse and hold another assembly.','Keep the protest as leverage.','The assembly brings another night of pressure. Exhausted volunteers ask who will cover the next shift. An exit must now be decided.',{mob:-5,leg:-4,access:-1},{pull:'social'})],'DEVELOPING · TALKS OFFERED')];
function currentTurn(){return state.turn>=1&&state.turn<=3?(state.branch==='leave'?LEAVE:STAY)[state.turn-1]:TURNS[state.turn];}
function charterName(){return {education:'education reform',rights:'student rights',youth:'young people’s lives',democracy:'democratic accountability'}[state.charter]||'the existing charter';}
function structureName(){return {central:'a national executive',federated:'a federation',membership:'a membership organisation',council:'an alliance council',open:'an open platform'}[state.structure]||'a decision process';}
const MINI={
assurance:scene('On Whose Authority?','“Before the last tents come down, your negotiators call. The Government says the cases will be withdrawn. They need to know what they may accept.”','What assurance do you need?',[
choice('written','A written commitment from the responsible authority.','Ask for a named office and a dated record.','Negotiations take another night. You leave with a signed commitment. It is not itself a withdrawal order.',{mob:-3},{set:()=>{state.assurance='written';state.flags.add('ASSURANCE_AUTHORITY_VERIFIED');}}),
choice('minister','A senior minister’s public assurance.','Ask for the promise on camera.','The words lead the evening news. Administrative instructions are still awaited.',{rel:2},{set:()=>state.assurance='minister'}),
choice('intermediary','An assurance through a trusted intermediary.','Let the negotiator vouch for the understanding.','The intermediary asks you to keep the exchange private. The promise now rests on a relationship.',{access:1},{set:()=>state.assurance='intermediary'}),
choice('resignation','The resignation is enough.','End the protest without another commitment.','The tents come down. No case-withdrawal agreement has been secured.',{leg:2},{set:()=>state.assurance='resignation'})],'NEGOTIATING TEAM · ON THE PHONE'),
charter:scene('Bigger Than What?','“The call to continue has been cheered. Representatives now ask what tomorrow’s demands will be. Some came for education reform. Others say the police response has changed what this protest is about.”','What are you asking people to stay for?',[
choice('education','Reform the education system.','Extend the work to examinations, universities and schools.','You keep the programme centred on education. People seeking a wider fight ask where they fit.',{agn:3}),
choice('rights','Defend student rights.','Include policing, campus democracy and treatment of students.','The programme now includes how institutions treat students. Organisers need legal expertise and agreed principles.',{agn:2,breadth:-2}),
choice('youth','Organise around young people’s lives.','Include employment, housing, safety and discrimination.','The proposed constituency grows. So does the list of issues the team must understand.',{rel:2,agn:-3}),
choice('democracy','Make democratic accountability the mandate.','Support people unable to make institutions respond.','Some see the breakthrough in a broader light. Others ask whether this is still the movement they joined.',{agn:3,breadth:-3})],'LIVE · BESIDE THE STAGE'),
participants:scene('Who Builds It With You?','“Groups that brought lawyers, transport and students to the original protest want to know where they fit. New volunteers are asking where to sign up.”','Who will build the next phase?',[
choice('cjp','Expand CJP itself.','Invite people into a CJP-led national movement.','Allies ask why a shared victory is becoming a recruitment drive for CJP.',{ind:2,trust:-5}),
choice('existing','Keep the existing alliance together.','Make the original partners the core of the next phase.','Partners bring working relationships, along with their own affiliations and priorities.',{trust:5,perceived:-2}),
choice('open','Open a new coalition.','Invite student groups, creators and local movements.','Invitations spread quickly. Trust and obligations have yet to be negotiated.',{breadth:3,org:-2}),
choice('assembly','Let the camp constitute the movement.','Ask people and groups on the ground to form a representative assembly.','Participants expect a real say. The camp does not represent every absent supporter.',{leg:2,acc:2})],'REPORT · THE COORDINATION TENT'),
structure:scene('How Will This Work?','“Volunteers need a contact for tomorrow. Campus groups want to issue statements. Journalists have asked for a spokesperson. The programme still needs a way to make decisions.”','How will the movement act?',[
choice('central','Establish a national executive.','Appoint state and campus coordinators.','The appointments can be made quickly. The executive must now answer for the people it authorises.',{org:3,acc:-2}),
choice('federated','Build a federation.','Let units organise within a common charter.','Local units can act, but the boundaries of their authority still need agreement.',{mob:3,agn:-2}),
choice('membership','Build a membership organisation.','Register members and elect representatives.','Volunteers begin the roll. There is no elected body yet; the founders will eventually have to submit to one.',{acc:3,mob:-2}),
choice('council','Form an alliance council.','Ask organisations to nominate mandated delegates.','Delegates need instructions from their organisations before claiming a common mandate.',{trust:3,ind:-2},{need:allied,why:'The partners needed to form a working council are not currently committed.'}),
choice('open','Keep it open for now.','Let groups act while the movement finds its shape.','Initiatives keep coming. Nobody can reliably bind the movement to one position.',{mob:3,org:-3})],'FROM THE MEETING ROOM'),
funding:scene('Your Accountant Calls','“You have ₹4.7 lakh left. At the current burn rate, that is seven weeks. Researchers, travel and case follow-up cannot all run on goodwill.”','How will you fund the next phase?',[
choice('crowd','Crowdfunding.','Ask the audience to fund the work.','Donations arrive in spikes. Quiet months still need paid follow-up.'),choice('dues','Membership dues.','Ask members for a small recurring contribution.','Income can become regular. Members expect an accountable budget and provision for those who cannot pay.'),choice('grant','A philanthropic grant.','Seek restricted school research funding.','Verification is funded. General campaigning and legal defence are not covered.'),choice('donor','A large donor.','Accept one substantial contribution.','The runway lengthens. One person’s requests now carry financial weight.'),choice('volunteer','Volunteer-only work.','Cut paid work and narrow what you promise.','Contracts end. A smaller volunteer service remains, with slower response and uneven unpaid burdens.'),choice('political','Political support.','Accept staff, offices and transport from a party.','Bills fall immediately. Party staff expect consultation before your next public attack.')],'INTERNAL · ACCOUNTS'),
exit:scene('The Last Night at the Camp',()=> '“Negotiations have produced '+(state.access?'a route for further discussion':'no settled agreement')+'. Volunteers say the next week’s rota cannot be filled. The public assembly is waiting for instructions about the tents.”','How do you close the protest camp?',[
choice('calendar','Publish the outstanding cases and a monitoring calendar.','Name what remains unresolved as people leave.','The tents come down with a public list of unfinished work. It still needs people to follow each case.',{acc:4,mob:-5},{set:()=>{state.flags.add('CLEAR_SETTLEMENT');}}),
choice('joint','Seek a joint phased withdrawal.','Have partners explain the departure together.','Groups agree to close the camp in stages. Nobody gets to claim the entire settlement.',{trust:4,mob:-5},{need:allied,why:'There is not enough active agreement for a joint withdrawal.'}),
choice('close','Close the camp without another agreement.','Let exhausted participants return to their lives.','The protest camp closes. Some call it necessary; others ask what another week would have achieved. The original cases remain work for another day.',{mob:-8,leg:-3})],'LIVE · THE EXIT'),
agenda:scene('Before the Statement Goes Out',()=> `“The draft changes the movement’s programme. People who joined around ${charterName()} want to know who approved the change.”`,'How do you authorise it?',[
choice('ratify','Submit it through the agreed decision process.','Wait for the body or partners who hold the mandate.','The public statement is delayed while representatives agree its scope.',{acc:3,mob:-2},{set:()=>{state.charter=state.turn===6?'youth':state.charter;if(state.turn===6)state.flags.add('WIDENED_TO_YOUTH');}}),
choice('narrow','Keep the existing programme for now.','Refer adjacent cases to other organisations.','You publish a narrower statement and explain where requests will be referred.',{agn:2,rel:-2}),
choice('override','Announce the wider position provisionally.','Promise a later review.','The statement goes out before approval. Those who were meant to decide record their objection.',{acc:-5,trust:-5},{set:()=>{state.charter=state.turn===6?'youth':state.charter;if(state.turn===6)state.flags.add('WIDENED_TO_YOUTH');state.mandate='breached';}})],'INTERNAL · A DRAFT STATEMENT')};
function disputeScene(){
 const plans={central:[['Decide within the executive’s remit.','Give the press a position the leadership can authorise.','The executive owns the decision and the consequences.'],['Consult partners before adding disputed points.','Delay the press conference.','The cameras wait. Partners have time to respond.'],['Announce a wider position without agreement.','Promise to settle authority afterward.','Partners publicly reject the claim that they agreed.']],federated:[['Announce only the common charter.','Keep disputed additions out of the statement.','The joint claim is narrower, but local units recognise it.'],['Wait for units to approve additions.','Postpone the press conference.','Journalists wait while local units consult.'],['Let units state their own positions.','Identify each statement as local.','Several positions reach the cameras. None is a binding national line.']],membership:[['Give a temporary committee a narrow remit.','Record the limits before it speaks.','A temporary committee speaks within stated limits. It is not an elected mandate.'],['Wait for registration and representation.','Delay the disputed decision.','Participants wait while a real roll is assembled.'],['Let founders decide pending review.','Publish a date to revisit the decision.','Founders speak tonight. The promised review remains an obligation.']],council:[['Seek a statement from mandated delegates.','Let each organisation confirm its position.','Delegates return with instructions. The agreed statement leaves disputed points unresolved.'],['Publish agreed points and record dissent.','Make the limits of agreement public.','Partners see their reservations recorded rather than erased.'],['Issue a CJP-only statement.','Do not claim it represents the alliance.','CJP speaks in its own name. The alliance has not authorised the statement.']],open:[['Announce only the original agreed demands.','Keep wider claims out for now.','The narrow statement buys time; no new common authority has been created.'],['Let groups address the press separately.','Name each speaker’s organisation.','The press receives several answers about what happens next.'],['Claim a common position without a mandate.','Ask groups to settle disagreements afterward.','Other groups challenge your claim to speak for them.']]};
 const list=plans[state.structure||'open'];return scene(state.occupation?'11:40 PM · First Disagreement':'The First Joint Statement',()=> '“One group wants '+(state.charter==='youth'?'employment made tomorrow’s priority':'employment included')+'. Another wants case withdrawal settled first. A third objects to party representatives on the coordinating body. Journalists are already outside asking who leads the movement.”','What can you authorise now?',list.map((x,i)=>choice(String(i),x[0],x[1],x[2],i===0?{acc:2}:i===1?{trust:2,mob:-1}:{acc:-3,trust:-3},{set:()=>{state.mandate=i===2&&['central','open','membership'].includes(state.structure)?'breached':state.structure==='membership'?'interim':i===1?'limited':'interim';}})),'OUTSIDE THE MEETING');
}
function activeScene(){if(state.screen==='bulletin')return state.bulletin;return state.screen==='mini'?(state.mini==='dispute'?disputeScene():MINI[state.mini]):currentTurn();}
const EXTERNAL={
1:['Images of the restrictions circulate alongside your specific demands. People who stayed away offer supplies and support.','Coverage centres on disruption and disputed claims. Several parents ask students not to return.','Committed supporters organise more intensely. Less political participants quietly step back.','The public story does not shift significantly. The work continues.'],
3:['Partners recognise the work and stay committed to the next phase.','A partner publicly distances itself and withdraws practical help.','Some partners remain, while others insist on limiting their involvement.','The response is routine; no new rupture follows.'],
5:['The hostile label fails to stick with many of the families following your work.','The accusation becomes the dominant frame in several reports. Organisers receive worried calls.','Your core embraces the confrontation; hesitant students stop attending.','The label circulates without materially changing participation.'],
8:['The meeting brings recognition from people who had not taken the movement seriously.','The photograph becomes a story about co-option. Your explanation receives less attention.','Some welcome institutional recognition; others see the photograph as evidence of capture.','The meeting passes without a new public controversy.'],
10:['The complaint receives prompt attention. Initial protection is arranged; follow-up remains necessary.','The office delays. Families wait, and your team must continue pressing for registration and protection.','The complaint begins moving, but the protection request remains unresolved.','The case follows an ordinary administrative timetable. There is no shortcut.'],
11:['Collective rules hold as individuals make choices. The organisation keeps its name and working relationships.','Several organisers move their relationships into established parties. The remaining team struggles to keep the work going.','Some leaders leave; a smaller independent core continues.','Few immediate departures follow. The election still consumes attention.']};
function drawExternal(c){
 let pool=EXTERNAL[state.turn];if(!pool)return null;
 if(state.turn===1&&state.branch==='leave')pool=['Other organisers welcome the verified support. Students who had not approached you begin making contact.','Disputed claims circulate alongside your association with the new protests. Organisers ask what your team actually checked.','Your coverage gathers an enthusiastic audience, while some unaffiliated students remain cautious.','Other organisers continue their work without a notable change in how your contribution is received.'];
 if(state.turn===8&&c.id==='a')pool=['The public demands attract attention from people outside the consultation.','Other groups shape the consultation while your demands receive little coverage.','Some welcome your distance from Government; others ask how the demands will reach implementation.','Your refusal produces no new public controversy.'];
 if(state.turn===11&&!members()&&!council())pool=['Several organisers choose to keep working together. The existing team retains its relationships through the first round of offers.',...pool.slice(1)];
 let good=25,bad=25;
 if(state.leg>=65){good+=5;bad-=5;}
 if(state.turn===1){if(has('CLEAR_SETTLEMENT')){good+=10;bad-=5;}if(state.charter&&state.mandate==='breached')bad+=10;}
 if([3,10].includes(state.turn)){if(allied())good+=10;if(has('EXCLUDED_ALLIES')){good-=10;bad+=15;}}
 if([5,8].includes(state.turn)){if(has('SERVICE_CAPACITY'))good+=10;if(has('PUBLIC_RULES')){good+=10;bad-=5;}if(state.perceived<45)bad+=10;}
 if(state.turn===11){if((members()||council())&&state.vars.ind>=55){good+=10;bad-=10;}if(state.funding==='political'||state.vars.ind<40)bad+=10;}
 const weights=[Math.max(5,Math.min(60,good)),Math.max(5,Math.min(60,bad)),25,25];let roll=random()*weights.reduce((a,b)=>a+b,0),i=0;for(;i<3;i++){roll-=weights[i];if(roll<0)break;}
 if(i===0)change({leg:5,perceived:3,breadth:3});if(i===1)change({leg:-7,perceived:-6,breadth:-6});if(i===2)change({mob:5,breadth:-7});
 if(state.turn===3&&i===1)change({trust:-14});
 if(state.turn===8&&i===1&&has('TRANSPARENT_ACCESS')){change({access:-2});state.flags.add('MINUTES_DISPUTED');}
 if(state.turn===11&&i===1){change({ind:-9,org:-6});state.futurePull.absorption+=5;}
 const text=pool[i]+(state.turn===8&&i===1&&has('TRANSPARENT_ACCESS')?' The ministry also disputes the published account and cancels its next meeting.':'');
 const event={turn:state.turn,type:['positive','negative','mixed','quiet'][i],text,weights};state.events.push(event);return event;
}
function finances(){
 state.financeNote='';if(!state.funding||state.turn<5)return;
 const weeks=state.turn===8||state.turn===11?8:4;
 const income=state.funding==='dues'?weeks*(members()?40000:18000):state.funding==='crowd'?(state.vars.rel>65?190000:45000):0;
 state.cash=Math.max(0,state.cash+income-state.burn*weeks);
 if(state.cash===0){change({org:-5,mob:-3});state.financeNote='The account cannot cover the next payroll. Travel is cancelled and staff move cases to a smaller volunteer rota.';state.staff=state.funding==='volunteer'&&has('BUILT_LEGAL_INFRASTRUCTURE');}
 else state.financeNote='The account holds ₹'+(state.cash/100000).toFixed(1)+' lakh. '+({dues:'Members ask to see the budget.',crowd:'Another appeal competes with case work.',grant:'Research funds cannot cover general legal defence or election work.',donor:'The donor asks for a private briefing.',volunteer:'The unpaid rota has a growing queue.',political:'Party staff ask to review your next statement.'}[state.funding]);
 if(state.funding==='donor'||state.funding==='political')change({ind:-2});
 if(state.funding==='grant'&&state.turn===10){state.financeNote+=' Unfunded legal work needs outside help.';state.staff=false;}
}
function govtResponse(){
 state.govtNote=state.vars.rel<35?'The office acknowledges your letter but meets a different youth organisation.':state.charter==='democracy'||has('ELECTORAL_INTENT')?'A spokesperson discusses your political ambitions instead of answering the demands.':state.vars.org>=55?'An official asks for a documented proposal and an authorised negotiating team.':state.occupation?'Officials ask again what would make the protest end.':'The responsible office offers a narrow administrative reply.';
 // A government perception is a response, not an automatic gift of access.
}
function applySelection(i,mini=false){
 if(state.screen!==(mini?'mini':'turn'))return;
 const sc=activeScene(),c=sc.choices[i];if(!c||(c.need&&!c.need()))return;
 state.decisionQuality=c.quality?c.quality():null;const before={...state.vars};const context={turn:state.turn,mini,key:state.mini,leader:state.leader,flags:new Set(state.flags)};const out=typeof c.out==='function'?c.out():c.out;
 change(c.effect);c.set?.();if(c.pull)state.futurePull[c.pull]+=mini?1:4;
 if(mini){
  const kind=state.mini;
  if(kind==='charter'){state.charter=c.id;state.flags.add('WIDENED_AGENDA');if(['youth','democracy','rights'].includes(c.id))state.flags.add('WIDENED_TO_YOUTH');}
  if(kind==='participants'){state.participants=c.id;if(c.id==='existing')state.flags.add('COALITION_CAPACITY');}
  if(kind==='structure'){state.structure=c.id;state.governance=null;state.flags.delete('MEMBERSHIP_GOVERNANCE');if(state.participants==='assembly'&&c.id==='central')change({trust:-5});if(state.branch==='leave'||state.turn>=4)state.pending.push({structure:true,due:state.turn+1});}
  if(kind==='funding'){
   state.funding=c.id;const f={crowd:[350000,75000],dues:[200000,55000],grant:[450000,60000],donor:[1100000,65000],volunteer:[0,10000],political:[900000,40000]}[c.id];state.cash+=f[0];state.burn=f[1];
   if(c.id==='donor')change({ind:-12});if(c.id==='political'){change({ind:-22,perceived:-12});state.futurePull.absorption+=8;}if(c.id==='volunteer')change({org:-8});
  }
  if(kind==='exit')state.occupation=false;
 }else{
  finances();govtResponse();
  if(state.turn===2&&state.branch==='leave')state.queue.push('relents');
  if(state.turn===3&&state.branch==='stay')state.queue.push('exit');
  if(state.turn===4)state.queue.push('funding');
 }
 recordDecision(c,context);refreshCapabilities();
 const directImpact=Object.fromEntries(Object.keys(before).map(k=>[k,state.vars[k]-before[k]]));
 const event=mini?null:drawExternal(c);
 const h={turn:state.turn,mini,event:sc.event,choiceId:c.id,label:c.label,consequence:out,external:event?.text||'',pull:c.pull||null,impact:Object.fromEntries(Object.keys(before).map(k=>[k,state.vars[k]-before[k]])),key:mini?state.mini:state.branch,tags:decisionTags(c,context),leaderImpact:state.leader-context.leader,directImpact};
 state.history.push(h);state.lastChoice={choice:c,text:out,turn:sc,external:event?.text||'',mini};state.screen='outcome';render();window.scrollTo(0,0);
}
function selectChoice(i){applySelection(i,false);}function chooseMini(i){applySelection(i,true);}
function nextTurn(){
 if(!['outcome','bulletin'].includes(state.screen))return;
 if(state.queue.length){const next=state.queue.shift();if(['midnight','relents'].includes(next)){enterBulletin(next);return;}state.mini=next;state.screen='mini';render();window.scrollTo(0,0);return;}
 if(state.turn===11){showEnding();return;}
 state.turn+=state.turn===1&&state.widened?2:1;state.space=SPACE[state.turn];state.mini=null;if(state.turn===11&&has('TEMP_MLA_LEVERAGE')){change({leverage:-4});state.flags.delete('TEMP_MLA_LEVERAGE');}
 for(const p of state.pending.filter(p=>p.due<=state.turn)){if(p.structure)completeStructure();else state.flags.add(p.flag);}
 state.pending=state.pending.filter(p=>p.due>state.turn);
 if(state.trust<35){state.flags.delete('COALITION_CAPACITY');if(state.governance==='council')state.governance=null;}
 refreshCapabilities();state.screen='turn';render();window.scrollTo(0,0);
}
function startGame(){state.screen='turn';render();window.scrollTo(0,0);}function showEnding(){state.screen='ending';render();window.scrollTo(0,0);}
function calculateEnding(){
 const v=state.vars;const capacity=v.org*.24+v.acc*.18+v.mob*.15+v.agn*.13+v.rel*.12+state.leg*.10+state.breadth*.08;
 const scores={party:state.futurePull.party+v.org*.2+v.mob*.2+v.agn*.15+(members()?8:0),lobby:state.futurePull.lobby+(has('EVIDENCE_CAPACITY')?12:0)+(legal()?8:0)+(allied()?7:0)+state.access*4+v.acc*.18,social:state.futurePull.social+v.rel*.2+(v.org<40?10:0),absorption:state.futurePull.absorption+(100-v.ind)*.3+(state.funding==='political'?10:0)+(has('INDIVIDUAL_DEALS')&&!members()&&!council()?6:0)};
 // Institutional migration requires loss of actual autonomy, not mere accusation.
 let future=Object.keys(scores).filter(k=>k!=='absorption'&&(state.structure!=='open'||k==='social')).sort((a,b)=>scores[b]-scores[a])[0];
 if(v.ind<45&&scores.absorption>=scores[future]-8)future='absorption';
 const endState=state.structure!=='open'&&capacity>=65&&v.org>=50&&v.acc>=45&&state.leg>=40?'THRIVE':capacity>=44&&v.rel>=30&&state.leg>=30?'RELEVANCE':'SURVIVAL';
 return {capacity,scores,future,endState};
}
function movementDiagnosis(e){
 const status=e.future==='absorption'?'ABSORBED':{THRIVE:'THRIVED',RELEVANCE:'RELEVANT',SURVIVAL:'SURVIVED'}[e.endState];
 return {state:status,form:{party:'Independent Youth Political Force',lobby:status==='THRIVED'?'Mass Pressure Organisation':'Independent Youth Pressure Organisation',social:'Social-Media Movement',absorption:'Movement Incorporated into Established Politics'}[e.future],text:{THRIVED:'You turned the opening into enough organisation, accountable decisions and usable relationships to remain a political actor. Other institutions must respond to work that continues after the original crowd has gone.',RELEVANT:'You no longer own the political space, but politics still has to account for you. Some of the work can survive beyond a campaign; other commitments still depend on a fragile team.',SURVIVED:'The movement remains, but much of the political capital it created has gone elsewhere. Continuing to exist has not guaranteed the ability to protect participants, deliver outcomes or gather a wider constituency.',ABSORBED:e.endState==='THRIVE'?'Your people entered established politics from a position of strength. The agenda survived the transition. The independence did not. The organisation you built helped determine the terms, but another political formation inherited the work.':'Your demands and relationships survived more readily than your independent organisation. Established politics inherited much of the capacity to act on the constituency you opened.'}[status],closing:{THRIVED:'The moment ended. The institution remained.',RELEVANT:'You still matter. But you no longer own the moment.',SURVIVED:'You can still create a moment. You can no longer decide what happens to it.',ABSORBED:'You changed politics. Someone else inherited the organisation of that change.'}[status]};
}
function endingCauses(e){return state.history.filter(h=>!h.automatic).map((h,i)=>({h,i,weight:(h.pull===e.future?8:0)+Object.values(h.impact).reduce((a,b)=>a+Math.abs(b),0)*.3+(e.future==='absorption'?Math.max(0,-h.impact.ind)*2:Math.max(0,h.impact.org)*.8)})).sort((a,b)=>b.weight-a.weight).slice(0,4).sort((a,b)=>a.i-b.i).map(x=>x.h);}
function momentMap(){const rows=[['Government policy','The resignation and adopted demands give the Government its own account of change.'],['Opposition politics',state.vars.ind<45?'Political relationships and organisers increasingly work through established parties.':'Parties borrow parts of your agenda without necessarily controlling your organisation.'],['Your organisation',state.vars.org>=50?'Records, routines and people continue beyond the original mobilisation.':'The name survives more easily than the routines needed to keep its promises.'],['Other movements',allied()?'Partners carry shared methods and relationships into struggles you do not lead.':'Other groups use the example, even where working relationships did not last.'],['The news cycle',state.vars.rel>=50?'Your campaigns still attract attention; follow-through remains a separate task.':'The images recede as the next crisis inherits the audience.']];return `<section class="moment-map"><h3 class="display">Where did your moment go?</h3><p>The people and institutions carrying the year forward.</p>${rows.map(r=>`<div class="migration"><strong>${r[0]}</strong><p>${r[1]}</p></div>`).join('')}</section>`;}
function optionsHTML(sc,mini){return sc.choices.map((c,i)=>{const unavailable=c.need&&!c.need();return `<button class="choice-card${unavailable?' locked':''}" ${unavailable?'disabled':''} onclick="${mini?'chooseMini':'selectChoice'}(${i})"><span class="choice-letter" aria-hidden="true">${String.fromCharCode(65+i)}</span><span class="choice-label" style="display:block">${c.label}</span><span class="choice-desc" style="display:block">${unavailable?(typeof c.why==='function'?c.why():c.why):c.desc}</span></button>`;}).join('');}
function renderTurn(){const sc=currentTurn();app.innerHTML=`<div class="screen"><div class="turn-header"><div class="phase-label">${sc.tag} · Turn ${state.turn+1} of 12</div><h2 class="turn-event display">${sc.event}</h2></div><div class="turn-situation">${typeof sc.report==='function'?sc.report():sc.report}</div><div class="turn-question display">${sc.question}</div><div class="choices">${optionsHTML(sc,false)}</div></div>`;}
function renderMini(){const sc=activeScene();app.innerHTML=`<div class="screen"><div class="phase-label">${sc.tag}</div><h2 class="turn-event display">${sc.event}</h2><div class="turn-situation">${typeof sc.report==='function'?sc.report():sc.report}</div><div class="turn-question display">${sc.question}</div><div class="choices">${optionsHTML(sc,true)}</div></div>`;}
function renderOutcome(){const l=state.lastChoice;app.innerHTML=`<div class="screen"><div class="turn-header"><div class="phase-label">${l.turn.tag}</div><h2 class="turn-event display">${l.turn.event}</h2></div><div class="outcome-chose">You said</div><div class="outcome-label display">${l.choice.label}</div><div class="outcome-text">${l.text}</div>${l.external?`<div class="outcome-text external-report"><span class="phase-label">Later reports</span><p>${l.external}</p></div>`:''}${!l.mini?`<div class="dispatches"><div class="dispatch dispatch-space">${state.govtNote}</div>${state.financeNote?`<div class="dispatch dispatch-warning">${state.financeNote}</div>`:''}</div>`:''}<button class="btn" onclick="nextTurn()">${state.turn===11&&!state.queue.length?'See your ending':'Continue'}</button></div>`;}
function renderEnding(){const e=calculateEnding(),d=movementDiagnosis(e);const causes=endingCauses(e);const reaction=[...state.events].reverse().find(x=>x.text&&x.type!=='quiet');app.innerHTML=`<div class="screen ending-screen"><div class="ending-state">Your movement after one year</div><h2 class="ending-state-value ${d.state.toLowerCase()} display">${d.state}</h2><div class="ending-future">${d.verb} · ${d.form}</div><div class="ending-diagnosis display">${d.text}</div><section class="ending-causes"><h3 class="display">The decisions that brought you here</h3><p>Your choices, and the commitments they created.</p><ol>${causes.map(h=>`<li><strong>${h.label}</strong><p>${h.consequence}</p></li>`).join('')}</ol></section>${reaction?`<div class="ending-diagnosis"><span class="phase-label">A response you encountered</span><p>${reaction.text}</p></div>`:''}<p class="ending-diagnosis display"><strong>${d.closing}</strong></p>${momentMap()}<details class="ending-trace"><summary>Review all your decisions</summary>${state.history.map(h=>`<div class="trace-item"><span class="trace-turn">${h.mini?'↳':h.turn+1}</span><span>${h.event}: <strong>${h.label}</strong></span></div>`).join('')}</details><p class="ending-diagnosis display">You asked for change.<br>You got it.<br><br>The question was never whether the moment survived.<br>It was who learned how to use it.</p><div class="ending-buttons"><button class="btn" onclick="resetGame()">Play Again</button></div></div>`;}
function renderTitle(){} // Replaced by the established photographic opening.
function render(){if(state.screen==='title')renderTitle();else if(state.screen==='turn')renderTurn();else if(state.screen==='mini')renderMini();else if(state.screen==='outcome')renderOutcome();else if(state.screen==='bulletin')renderBulletin();else renderEnding();}
window.advanceTime=()=>{};
window.render_game_to_text=()=>JSON.stringify({screen:state.screen,turn:state.turn+1,event:state.screen==='bulletin'?state.bulletin.event:state.screen==='outcome'?state.lastChoice.turn.event:state.screen==='mini'?activeScene().event:currentTurn()?.event,choices:['turn','mini'].includes(state.screen)?activeScene().choices.map(c=>({label:c.label,available:!c.need||c.need(),description:c.need&&!c.need()?(typeof c.why==='function'?c.why():c.why):c.desc})):[],outcome:state.screen==='outcome'?state.lastChoice.text:undefined,report:state.screen==='bulletin'?state.bulletin.report:state.screen==='outcome'?state.lastChoice.external:undefined,ending:state.screen==='ending'?movementDiagnosis(calculateEnding()):undefined});
